src/encoder.cc, src/tsencoder.hh
Use static_cast instead of reinterpret_cast to cast to and from void* as
the address is preserved as specified in the standard.
=> Fix unnecessary reinterpret casts

demos/encoder/main.cc, demos/encoder_hots/main.cc, inc/encoderfoaw.h, inc/encoderhots.h, src/encoderfoaw.hh, src/encoderhots.hh
Standardize encoder naming by placing algorithm acronym as a suffix and
avoiding all uppercase.
=> Rename Encoder classes

inc/encoderfoaw.h, src/encoderfoaw.hh
While velocity() requires member variables in EncoderFoaw to be mutable,
the method is marked const as only the internal fields of the class are
modified.
=> Define EncoderFoaw::velocity() as a const member function

projects/flimnap/main.cc, projects/inc/saconfig.h
Include the roller to rear wheel ratio in RLS_GTS35_ENC_CFG to give the
encoder count for the rear wheel directly. Increase counts per
revolution by 4x as 48 is the number of slots and not equal to counts
when the encoder is used in quadrature.
Forward velocity v is positive for negative rear wheel angular velocity
and is redefined accordingly.
=> Fix rear wheel angle and forward velocity calculations

projects/flimnap/main.cc
Remove extra factors used when computing torque command for handlebar
motor. Cast torque value to a signed int type before a saturated value
has been calculated.
=> Fix scaling of Kollmorgen torque command

inc/foaw.h, src/encoderfoaw.hh, src/foaw.hh
Add new argument 'overflow_value' to foah::estimate_velocity() with
default value of 0. This argument represents a positive value with would
cause the underlying data to overflow; this commonly occurs with
encoders. If positive, the position buffer elements will be modified in
place if overflow or underflow is detected during the velocity
estimation calculation. The buffer elements will be restored at the end.
=> Handle position overflow in FOAH velocity estimation

demos/pwm_encoder/main.cc
This fixes a build warning introduced by the following commit:
7f64b6445ac0154cc967406a8985c0d464d94017
=> Add missing EncoderConfig field

projects/src/simplebicycle.cc
Limit Newton-Raphson iterations when solving for pitch angle constraint
to 3. In normal cases, the pitch angle can be solved in 1 to 2
constraints. It is only in extreme/unrealistic configurations where the
number of iterations increases, but these do not result in realistic
pitch values, so there is no reason to expend computation time.
=> Limit pitch constraint iterations

src/packet/frame.cc
The source byte size check no longer always returns true after commit
16619b5a4c6741ce21cee1f5370725b59016929a.
=> Re-enable frame::unstuff source byte size check

projects/inc/saconfig.h
Define steer assembly inertia about the steering axis for configurations
with and without weight plates based on experimental data. Use steer
assembly inertia with weight plates as default.
Data and calculation are available here:
https://drive.google.com/drive/folders/0B0TYqj2SzQN5MWx6eU04cmVHMnc?usp=sharing
=> Use measured steer assembly inertia

src/analog.cc
The Kistler torque sensor output is not valid unless the measure line is
enabled after the sensor is powered on. In the Analog class, we simply
toggle the measure line before starting the ADC driver.
=> Fix Kistler torque sensor initialization

projects/inc/simbicycle.h, projects/src/simbicycle.hh
Remove roll angle limit when not using the BicycleKinematic model. Rate
saturation is retained.
=> Disable roll angle saturation

.editorconfig
The .editorconfig serves as a cross-editor configuration, assuming your editor
has an editorconfig plugin installed and enabled.
=> :sparkles: Add editorconfig

projects/flimnap/main.cc
Change the bicycle fixed velocity in Flimnap from 7.0 m/s to 5.0 m/s.
For the Whipple model with benchmark parameters, this is within the
stable range.
=> Change bicycle fixed velocity to 5.0 m/s

projects/CMakeLists.txt, projects/flimnap/CMakeLists.txt
Replace CMake build option PHOBOS_BUILD_PROJECT_FLIMNAP with the two
options PHOBOS_BUILD_PROJECT_FLIMNAP_WHIPPLE and
PHOBOS_BUILD_PROJECT_FLIMNAP_KINEMATIC allowing use of either model.
This allows a specific version to be built and used with CMake openocd
options.
=> Split Flimnap CMake build option

.travis.yml, CMakeLists.txt
Change Travis to run five build environments, three compiling embedded
code and two for host code. Build host tools and tests with gcc and
clang.
Fixes #110
=> Test clang builds on Travis

scripts/icsc2017/generate_figures.py, scripts/plot_sim.py
Add option to function plot_states() in plot_sim to enable a second y
axis in state plots. The angle signals are plotted with the left y axis
and the rate signals are plotted on the right y axis.
=> Add option to plot_states for a second y axis

projects/CMakeLists.txt, projects/flimnap/CMakeLists.txt, projects/flimnap/main.cc, projects/inc/saconfig.h, scripts/plot_sim.py
Steer encoder index position and upper assembly virtual inertia need to be updated after the steering assembly was disassembled and reassembled.
=> Update system physical constants after reassembly

inc/cobs.h, src/cobs.cc, tests/test_cobs.cc, tests/test_cobs_random.cc
EncodeResult.written becomes EncodeResult.produced. Its value is only useful
when the status is OK so in other cases it is set to 0.
DecodeResult.read becomes DecodeResult.consumed. Its value is only useful
when the status is OK or UNEXPECTED_ZERO so in other cases it is set to 0. This
makes things slightly easier for code calling `cobs::decode`.
DecodeResult.written becomes DecodeResult.produced. Its value is only useful
when the status is OK so in other cases it is set to 0.
=> Change meaning of COBS result object fields

projects/inc/simbicycle.h, projects/src/simbicycle.hh
The input vector u is calculated from torque sensor measurements and
inertia properties of the system. This adds a member variable to
sim::Bicycle to store and access the most recently computed input,
allowing code calling the update_dynamics() member function to obtain
the roll torque and steer torque used in model simulation.
=> Store computed input in sim::Bicycle

projects/clustril/main.cc, projects/flimnap/main.cc, projects/inc/simbicycle.h, projects/src/simbicycle.hh
Handlebar feedback is independent of the bicycle simulation. The bicycle
simulation class should not compute handlebar feedback torque nor should
it have a handlebar object member variable.
Fixes #159
=> Remove Haptic template argument from sim::Bicycle

projects/flimnap/main.cc, projects/inc/simbicycle.h, projects/src/simbicycle.hh
The Oracle observer doesn't do anything so we shouldn't use it.
Fixes #231
=> Remove Oracle observer

projects/inc/transmitter.h
Use of the maximum encoded size of messages for size of transmitter
serialization buffer to prevent serialization errors for a full message.
=> Fix size of transmitter serialization buffer
