demos/encoder/CMakeLists.txt, demos/encoder/main.cc, inc/encoderfoaw.h, inc/encoderhots.h, inc/foaw.h, inc/iqhandler.h, src/encoderfoaw.hh, src/encoderhots.hh, src/foaw.hh, src/iqhandler.hh
Add class that handles data sampled in an ISR and inserts it into a
circular buffer. Allows delayed insertions in the event the circular
buffer is in use.
=> Add IQHandler class

src/encoderfoaw.hh
Arm sample timer with period in system ticks.
=> Fix timer period when in EncoderFoaw

.travis.yml, README.md, travis/checkout-submodules.sh, travis/install-protobuf.sh
When installing protobuf, check if protobuf and protobuf-python are
installed separately.
=> Speedup Travis protobuf install

scripts/phobos/display.py, scripts/plot_pose.py
Calculate time difference between pose timestamp values and add as a
subplot to pose plots. This field has millisecond resolution.
=> Plot dt in pose plots

tools/pbprint.cc
Set baud_rate to 0 to use pbprint on a protobuf stream file.
=> Allow file input to pbprint

CMakeLists.txt, projects/flimnap/CMakeLists.txt, projects/flimnap/main.cc, projects/inc/messageutil.h, projects/src/simbicycle.hh
=> Add bicycle kinematic model

README.md, projects/CMakeLists.txt, projects/hall/CMakeLists.txt, projects/hall/chconf.h, projects/hall/halconf.h, projects/hall/main.cc, projects/hall/mcuconf.h
This project prints the realtime counter and torque values in adc
counts. Analog sample speed is increased to 8 kHz for this project and
is used for determining torque scaling values. Transmits value as ASCII
using serial over USB.
=> Add project Hall

projects/flimnap/main.cc, projects/inc/simbicycle.h, projects/src/simbicycle.hh
=> Add observer prime method

projects/inc/simbicycle.h, projects/src/simbicycle.hh
=> Refactor sim bicycle template parameters

travis/build.bash
...in the build folder.
Fixes #134
=> Run tests when the tests folder exists

scripts/phobos/constants.py, scripts/plot_sim.py
=> Remove duplicated constants

tests/test_cobs.cc
=> Add cobs error tests

scripts/phobos/constants.py
=> Remove printing of values in Python constants script

inc/cobs.h, src/cobs.cc
=> Enable cobs length computations at compile time

projects/flimnap/chconf.h, projects/flimnap/main.cc, projects/inc/simbicycle.h, scripts/load_sim.py
=> Increase simulation loop rate

projects/flimnap/main.cc
Set the pose in the transferred messages so that we can visualize the bicycle.
=> Send simulation pose

projects/flimnap/main.cc, projects/src/simbicycle.hh
Take modulo of pose rear wheel angle with modulus two pi to prevent rear
wheel angle from continuously increasing.
Fixes #193
=> Normalize pose rear wheel angle

projects/inc/simbicycle.h, projects/src/simbicycle.hh
=> Fix semaphore access for simbicycle full state

projects/flimnap/main.cc, scripts/plot_sim.py
Use the measured physical upper assembly inertia value for calculation
of upper assembly inertia torque.
=> Fix handlebar inertia value

tools/pbprint.cc
Fixes https://github.com/oliverlee/phobos/issues/214
=> :sparkles: Allow pbprint to read from file

README.md, demos/adc/README.md, demos/bicycle/README.md, demos/dac/README.md, demos/eigen/README.md, demos/encoder/README.md, demos/encoder_hots/README.md, demos/encoder_index/README.md, demos/fatfs/README.md, demos/gpt_adc/README.md, demos/pwm_encoder/README.md, demos/usb_serial/README.md, projects/clustril/README.md, projects/drunlo/README.md, projects/flimnap/README.md, projects/gulliver/README.md, projects/hall/README.md
Fixes https://github.com/oliverlee/phobos/issues/182.
=> Update readme files

projects/flimnap/main.cc, projects/inc/interpolated_lqr.h, projects/inc/simbicycle.h, projects/src/simbicycle.hh, scripts/calculate_lqr_gain.py, scripts/load_sim.py
This PR reimplements https://github.com/oliverlee/phobos/pull/191
Fixes #169, https://github.com/oliverlee/phobos/issues/218
~~This PR depends on #213~~
=> Add low speed roll assistance

inc/filter/median.h, inc/filter/movingaverage.h
Fixes https://github.com/oliverlee/phobos/issues/143
=> Document moving average overflow

projects/flimnap/main.cc
Reduce Kalman Q values in flimnap-whipple to improve response to steer
torque input.
=> Reduce Kalman filter process noise covariance values

scripts/calculate_lqr_gain.py
Change printing of LQR gain elements for easier copying.
=> Change LQR gain element printing

CMakeLists.txt, inc/utility.h, projects/CMakeLists.txt, projects/flimnap/CMakeLists.txt, projects/flimnap/README.md, projects/flimnap/main.cc, projects/inc/haptic.h, projects/inc/simbicycle.h, projects/src/haptic.cc, projects/src/simbicycle.hh, scripts/plot_sim.py
implementation checklist:
Fixes #161
This PR is dependent on the following: ~~https://github.com/oliverlee/phobos/pull/204~~, ~~https://github.com/oliverlee/phobos/pull/213~~, ~~https://github.com/oliverlee/bicycle/pull/22~~
=> Add simplified haptic calculation

projects/CMakeLists.txt, projects/flimnap/CMakeLists.txt, projects/flimnap/main.cc
Remove invalid simplified bicycle model.
=> Remove flimnap Arend variant

inc/filter/polyfit.h
Add class to perform polynomial fitting to periodically sampled data.
=> Add polynomial fit class

scripts/plot_sim.py
Use logged controller error and error derivative signals instead of
calculating.
=> Plot controller error and error derivative
